# Generated by Django 3.2.23 on 2024-02-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_customerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemoglobin', models.IntegerField(blank=True, null=True)),
                ('rbc_count', models.IntegerField(blank=True, null=True)),
                ('pcv', models.IntegerField(blank=True, null=True)),
                ('rdw', models.IntegerField(blank=True, null=True)),
                ('platelet_count', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(null=True, upload_to='user_docs/')),
                ('date', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
